### ISSUE TITLE
There is no automated build

### ISSUE THREAD

**Issue by JamesLTaylor** [JamesLTaylor/QuantSA#22]
At a minimum:
- compile source
- run tests
- check that all example sheets open and have no errors
- (maybe) update md help files

**Comment by Robertj1983** [comment]
The use of Excel as part of the build process will necessitate a custom build machine setup, perhaps a VM in the cloud with the appropriate software loaded, and a CI system setup.

**Comment by JamesLTaylor** [comment]
Build is running but without excel tests
